#端口
server:
  port: 8124
  servlet:
    #上下文
    context-path: /
    #编码格式
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  #编码格式
  tomcat.uri-encoding: UTF-8

spring:
  #上传文件修改限制大小
  servlet.multipart:
    max-request-size: 100MB
    max-file-size: 10MB
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    database.type: mysql
    url: jdbc:mysql://39.107.157.91:13306/dashu_frame_open?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: dashuopen
    password: dashuopen@123
  #Redis配置
  redis:
    host: localhost
    port: 6379
    password:
    database: 7
  mvc:
    # 解决swagger2冲突，导致启动报错问题(@See：https://blog.csdn.net/mapboo/article/details/121568519)
    pathmatch.matching-strategy: ant_path_matcher
  #thymeleaf配置
  thymeleaf:
    enabled: true
    prefix: classpath:/static/
    suffix: .html
    encoding: UTF-8
    cache: false

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.kg.**.entity

#自定义配置
com.kg:
  #文件上传配置
  file:
    #允许上传的文件格式（防止攻击类脚本文件上传，以|结尾）
    allow-extend: jpg|jpeg|png|gif|bpm|mp3|mp4|doc|docx|xls|xlsx|pdf|zip|rar|txt|
    #允许上传的图片格式（图片需要压缩，格式必须正确，以|结尾）
    image-extend: jpg|jpeg|png|gif|bpm|
    #图片自动压缩，压缩比率（0-1之间的小数，例如：0.6表示压缩为60%）
    image-quality: 0.6
    #文件上传物理路径（文件保存的物理绝对路径;不要使用\；若使用docker部署，要配置容器内部路径，一般是/usr/local/springboot/））
    save-path: e:/IdeaProjects/fwwbsyb/dashu-frame-open/component/target/myupload/files
    #文件路径映射（对外访问的路径，通过spring映射到物理路径;不要使用\;要在security.ignore放开）
    url-pre: /upload
  #登录常量配置
  login:
    #是否单例登录
    is-only-one: false
    #登录是否需要验证验证码
    is-yzm: true
    #jwtToken过期时限，单位：分钟
    jwt-token-expiry: 120
  #开发管理员配置 (所有开发管理员的ids，多个用逗号隔开)
  developer-user-ids: 1
  #跨域配置，是否允许跨域：默认关闭（true开启；false关闭）
  cors-enable: false
  #默认操作日志，保存天数，默认：180天（定时任务自动删除旧日志）
  auto-operate-log: 180
  #验证码配置
  captcha:
    #类型枚举 ARITHMETIC-算数；CHINESE-中文；CHINESE_GIF-中文闪图；GIF-闪图；SPEC-常规
    type: ARITHMETIC
    #有效期 分钟
    expiration: 10
    #内容长度
    length: 4
    #图片宽高
    width: 163
    height: 49
    #字体样式
    font-family: Default
    font-size: 20
    #字体颜色（如：FFFFFF  允许为空，颜色随机）
    font-color:
    #0正常、1加粗、2斜体
    font-style: 0
    #背景色（如：FFFFFF  允许为空，透明图无背景色；注意：闪图不支持透明背景色）
    bg-color:
  #swagger相关配置
  swagger:
    enable: true
    title: "大树快速开发平台API"
    description: "基于swagger的Api接口信息"
    terms-of-service-url: "https://www.java119.cn"
    version: "1.0.0"
    concat:
      name: "ziro"
      www: "https://www.java119.cn"
      email: "877185959@qq.com"
  #oauth2配置
  oauth2:
    #服务端，是否启动(true/false)
    server.enable: true
    #客户端信息配置（作为Oauth2的客户端，集成第三方Oauth2统一认证登录时使用）
    client:
      clientId: dev
      clientSecret: qwer@123
      #回调地址
      redirectUri: http://localhost:8124/oauth2/client/login/code
      #第三方Oauth2服务端地址
      oauthServerUri: http://localhost:8124/
      #回调登录错误时，跳转前端错误页
      errorRouter: http://localhost:9532/#/oauth2/error
      #回调登录成功时，跳转前端成功页（处理本系统登录逻辑）
      successRouter: http://localhost:9532/#/oauth2/success
      #回调登录成功，但首次登录时，跳转到绑定用户界面
      userBindRouter: http://localhost:9532/#/oauth2/bind
  #微信配置
  weixin:
    #小程序配置(其中accessTokenUrl、jsCodeUrl、qrCodeUrl如需自定义，在此处配置即可覆盖默认值)
    applet:
      appId: xxxxx
      secret: xxxxx
    #服务号配置（见 WxMpLoginConfig.java）
    mp:
      #服务号appId
      clientId: wx089f5f07265e8026
      #服务号appSecret
      clientSecret: 8c8c6cf9b51b8f9bfc20337b92fa90dc
      #回调域名（有端口或上下文的要加上）（前后端分离，前端根目录）
      domain: http://58.57.95.202:19527
    #微信支付（商户号）配置（WxPayConfig.java）
    pay:
      #微信绑定的公众号appId
      #商户号只能绑定：已通过微信认证的服务号、政府或媒体类订阅号、小程序、企业微信、移动应用、网站应用
      appId: wx089f5f07265e8026
      #商户号mchId
      mchId: 1642005801
      #当前密钥版本(v2/v3)
      keyVersion: v2
      #商户号v2密钥
      partnerKey: 39a1c424d74111ed8b82005056ad6b1e
      #证书p12地址(v2退款时需要)
      certP12Path: pems/apiclient_cert.p12
      #商户号v3密钥
      partnerKeyV3: 39a1c424d74111ed8b82005056ad6b1e
      #证书pem地址(v3时需要)
      certPath: pems/apiclient_cert.pem
      #私钥pem地址(v3时需要)
      keyPath: pems/apiclient_key.pem
      #支付结果通知地址（后台接口地址：http://www.xxxx.com/api/）
      notifyUrl: http://www.xxxx.com/api/pay/wechat/payNotify
  #支付宝支付配置
  alipay:
    #应用id
    appId: 2021003141637400
    #支付宝私钥
    privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCRWjVGx5WhiA6mAqGewvyvT2D2+ef5mJlM6XFev2Z+9Fa01gtv3yt3Q2XKXgJK+tEFcf3crBUhu7TyK5xWHR4xJ1Rf1Mi6gPDQ86CO/CqjJK5T2u5GpVX+eJnGf6dR24skMaxQjsi8gxxK2vewJF8ZidXkOp8rQl+OKSsK7SStjdPO7xvVn8I1BznDyECHtde6XthbLbZSR/3DIq5qFdt5mv+rz0YIGTABVQMZRsrHG2v4uHYGOYM6M0m+H7EU19u7xlh8411RKVTRdo2NorLJqPHFGf0XY1cW8iQdEACgNy0N/CsGcoAUkGEgyeEc054d35I6IKVxj1qyU6ZsqlujAgMBAAECggEAPXfbnfIbajNClpv4Q06MU4sLI4btvhT1h5wVUI86xieIX3NBZO8Iz6fV7S2yZIkLSfU5+U9gpGJgFCWzOIuZ0Amk2d3/gTe0H3lYBf/H/DQv8NBeAcw7wKC5z0L+vFRO1GCZUXwAkhAUL+fH5VqMSR2MMbdExqOMC2+Hf1hoMWhr/8LXsgGRb3UHmZmvnTh/LQSN2z4HmPIWN9ylp6Pz3MbeFzvzQev5DgLV7zKMls2s0NeCwRd8riTP1xj0jRuVPm+M2cg8DkaiOVoxiFyjI3rtJvUa/+ipAc+xrfHdP10Gp4JxpMChyfXZQLhIrzf35Ikgbpz5AfQq84GtYHlqQQKBgQDWcSslEOJ62U+7otTFzMAMIZ8jTaWf9jivJI6qIz5xUR5SQI3LoJS/I6abMJfxmV5t9oOtWEmq6liY/vwYDosv6QZ0pKfw7T3kc3ZsBDxdGYnenAg4dpj2rNivCwKN8GGU00JU+uSMeemrJDSf93m+mxTP1s1XBFTE7hW8HCv8YQKBgQCthWJHnsq23ZeY5DAzXfizhUevN494FgKflMUWYziEbinL0Qu3CVFL6MtTud21gKobOFcq0y2A0ts3kaPdP2HUYdcEOd/VAKBK1oA9AIayNBQrY8uKXvjBeJ9g052PWMY3D898ZkIQzj4VNFA5PAfis8QJAZ0vtvl06fy2mIP2gwKBgBpphe7izYJkEbYCsEJMnbrgyUEH50Z0hTbNQeUiwiYi36Ex4kUaWjfQpEypB43yXfcdTcqj/S7X/mGZxmMQJ4SXJvxm62h5UA47SnKzctvksV6ByWFq+hwn3ehxarcgzGQQQTNGU7AZs/YoV3L8gDpBz6ZpxpDZL7exu2uX7LMBAoGAaJ16W2PJI+cFdxBcXxvQzasVRPZicSwT+NJg4NaBRJaGbHNkdL4RXYrEy33LxZoE9NRK+W7IiFqYADC2crW77afvUoTyBiGSgoxAVIb0rovnfSF1nb8UitCGhoIPBFWpa5kEpyOfwTIXDAG2PEuNFYj8L9HhStsuGubXjd718LECgYEAwMQcyvSXBpGKs/xfRX1M+hUG7GXGU72PpX7N7fmNiIiOld+DZrzgScvoDB5RTKd30IWliIR/DValmnRZFjmkOd5WVOe+u0aTsN2E8/gi9QSV4WejVVOMOM8GBSibXw7WdT50pHfB+RmTxhpFQOzaBk6UclhHSUgWszgo2C5uKKA=
    #支付宝的公钥（注意：非应用公钥）
    aliPayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnUJF8NcAbbBdU0PHfNsncqVVLWXLO56sNso/u/Q/AumyQtWOMuYCor2XVp465ZKzWG7VLmyJtJezSB4hPTnIIGepk+DJgfD8l2QPFySOl8darBJ6MHXwPtEQuQ4/ZG8JpHAP11uHQtohdvaFEAfl4BZDE1pA7YDFkSTyhqiEgJtDYtAf0Xik52s1rpoGykCoEKef1TqwwqbaZ+iUmNGEDLwOIA8Klt9TaXOHOJaaY9D54OVvGFVznsMeK6J2SlVHtSVMq1OEkxnmFffXAIKoNsY5nLYHLNelp5UWPEmV9QstWjAR+trke3u35/DbjcALz0m8AJbEuGKlMjrGQBOZQIDAQAB
    #支付结果通知地址（后台接口地址：http://www.xxxx.com/api/）
    notifyUrl: http://www.xxxx.com/api/pay/alipay/payNotify
    #支付返回地址
    returnUrl: http://www.xxxx.com/api/pay/alipay/returnUrl
  #百度OCR配置
  baidu:
    host: https://aip.baidubce.com/oauth/2.0/token
    client-id: xxxxx
    client-secret: xxxxx
    grant-type: xxxxx
  #短信通知相关配置
  sms:
    aliyun:
      accessKeyId: LTAI5t8EGvqGbyx7hAaEZDZg
      accessKeySecret: j7wunkgc1GCXTtMZ7gtphVWFuaNPt6
      endpoint: dysmsapi.aliyuncs.com
      sign: 阿里云短信测试

#输出日志配置（日志级别：trace/debug/info/warn/error）
logging.level:
  root: info
  com.kg: trace