#端口
server:
  port: 8123
  servlet:
    #上下文
    context-path: /
    #编码格式
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  #编码格式
  tomcat:
    uri-encoding: UTF-8

spring:
  #上传文件修改限制大小
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    database:
      type: mysql
    url: jdbc:mysql://39.107.157.91:13306/dashu_frame_open?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: dashuopen
    password: dashuopen@123
  #Redis配置
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.kg.**.entity

#自定义配置
com:
  kg:
    #微信配置
    weixin:
      appid: xxxxx
      secret: xxxxx
    #百度OCR配置
    baidu:
      clientId: xxxxx
      clientSecret: xxxxx
      grantType: xxxxx
    #文件上传配置
    file:
      #允许上传的文件格式（防止攻击类脚本文件上传）
      allow-extend: jpg|jpeg|png|gif|bpm|
      #允许上传的图片格式（图片需要压缩，格式必须正确）
      image-extend: jpg|jpeg|png|gif|bpm|
      #默认上传路径（文件保存的物理绝对路径;不要使用\）
      save-path: e:/IdeaProjects/fwwbsyb/dashu-frame-open/component/target/myupload/files
      #隐藏上传路径（用于访问的路径，通过spring代理;不要使用\;要在security.ignore放开）
      url-pre: /upload
    #swagger相关配置
    swagger:
      title: "大树快速开发平台API"
      description: "基于swagger的Api接口信息"
      termsOfServiceUrl: "http://www.keepgrown.com"
      version: "1.0.0"
      concat:
        name: "ziro"
        www: "http://www.keepgrown.com"
        email: "877185959@qq.com"
    #开发管理员配置
    developer:
      user:
        # 所有开发管理员的ids，多个用逗号隔开
        ids: 1
    #登录常量配置
    login:
      #登录是否需要验证验证码
      isYzm: true
      jwt:
        token:
          #token过期时限，单位：分钟
          expiry: 120
    #跨域配置
    cors:
      # 是否开启跨域：默认关闭（true开启；false关闭）
      enable: false
    #验证码配置
    captcha:
      #类型枚举 ARITHMETIC-算数；CHINESE-中文；CHINESE_GIF-中文闪图；GIF-闪图；SPEC-常规
      type: ARITHMETIC
      #有效期 分钟
      expiration: 10
      #内容长度
      length: 4
      #图片宽高
      width: 163
      height: 49
      #字体样式
      fontFamily: Default
      fontSize: 20
      #0正常、1加粗、2斜体
      fontStyle: 0
#输出日志配置
logging:
  level:
    root: info
    com:
      kg: trace